base_dir: "/home/security/dtuan/autorun"
iface: "eth0"
api_url_run_acc: "http://192.168.51.30:20168/run_acc"
api_url_run: "http://192.168.51.30:20168/run"
flamegraph_script: "/home/security/dtuan/FlameGraph/run_perf.sh"
xdp_prog_dir: "/home/security/dtuan/xdp-program"
xdp_prog_dir1: "/home/security/dtuan/xdp-program/xdp_prog"
rf_model_dir: "/home/security/dtuan/security_paper/rf"

xdp_program:
  kern_obj: "/home/security/dtuan/xdp-program/xdp_prog/xdp_prog_kern.o"
  stats_bin: "/home/security/dtuan/xdp-program/xdp_prog/xdp_stats"
  dump_bin: "/home/security/dtuan/xdp-program/xdp_prog/dump_map_to_csv"
  xdp_loader: "/home/security/dtuan/xdp-program/xdp_prog/xdp_loader"
  python_quickXDP: "/home/security/dtuan/xdp-program/xdp_prog/rf2qs.py"
  python_RF: "/home/security/dtuan/xdp-program/xdp_prog/read_model_to_map.py"
  throughput_script : "/home/security/dtuan/autorun/src/estimate_throughput_latency.py"

dataset:
  ground_truth: "/home/security/dtuan/security_paper/data/data.csv"
  output_dir_acc: "run_accuracy"

nn_scripts_path: "/home/security/dtuan/ebpf-classifier/nn-filter/nn_filter_xdp.py"
folder_out_nn: "/home/security/dtuan/ebpf-classifier/nn-filter/out"
logging:
  main_log: "acc_run.log"

# pcap_file: "/home/lanforge/Desktop/pcap/full_attack.pcap"
pcap_file: "/home/lanforge/Desktop/pcap/pi4_data.pcap"
scripst_tcpreplay: "/home/lanforge/Desktop/scripst_tcpreplay.sh"
iface_lanforge: "enp1s0f0"

results:
  bpf: "results_bpf"
  perf: "results_perf"
  lanforge: "/home/lanforge/Desktop/app/test"
  system_log: "log_all.log"
  throughput: "results_throughput"
